name: Build and Release Fabric Mod

on:
  push:
    tags:
      - 'release/v*.*.*'

jobs:
  build:
    name: Build and Release Fabric Mod
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read Java Version from Gradle
        run: echo "JAVA_VERSION=$(grep 'java_version' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Fabric mod
        run: gradle build

      - name: Find JAR file
        id: find_jar
        run: echo "JAR_FILE=$(find build/libs -maxdepth 1 -type f -name '*.jar' ! -name '*-sources.jar')" >> $GITHUB_ENV

      - name: Generate SHA256 checksum
        id: generate_checksum
        run: |
          SHA256=$(sha256sum ${{ env.JAR_FILE }} | cut -d ' ' -f 1)
          echo "$SHA256" >> SHA256_CHECKSUM.txt

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.JAR_FILE }},SHA256_CHECKSUM.txt"
          bodyFile: "CHANGELOG.md"
